# Generated by Django 4.2.6 on 2024-08-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_cardproduct_card'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardproduct',
            unique_together={('product',)},
        ),
        migrations.RemoveField(
            model_name='cardproduct',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
